services:
  scheduling-service:
    image: ${DOCKERHUB_USERNAME}/scheduling-service:latest
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: always

  attendance-service:
    image: ${DOCKERHUB_USERNAME}/attendance-service:latest
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - SCHEDULING_SERVICE_URL=http://scheduling-service:8000
      - AI_VISION_SERVICE_URL=http://ai-vision-service:8000
    depends_on:
      - scheduling-service
      - ai-vision-service
    restart: always

  ai-vision-service:
    image: ${DOCKERHUB_USERNAME}/ai-vision-service:latest
    ports:
      - "8003:8000"
    env_file:
      - .env
    restart: always
