apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
  namespace: smart-attendance
  labels:
    app: attendance-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
        - name: attendance-service
          image: DOCKERHUB_USERNAME_PLACEHOLDER/attendance-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: platform-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: smart-attendance
spec:
  type: ClusterIP
  selector:
    app: attendance-service
  ports:
    - port: 8000
      targetPort: 8000
