"""Initial schema

Revision ID: a2487db326cd
Revises: 
Create Date: 2026-07-22 08:27:41.179713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2487db326cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('academic_years',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year_level', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('name', name=op.f('uq_academic_years_name')),
    sa.UniqueConstraint('year_level', name=op.f('uq_academic_years_year_level'))
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('faculty_name', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_table('platform_settings',
    sa.Column('id', sa.String(), server_default='default', nullable=False),
    sa.Column('university_name', sa.String(), nullable=True),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('auto_approve_registrations', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('current_academic_year', sa.String(), nullable=True),
    sa.Column('default_late_threshold_minutes', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('default_random_window_minutes', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('default_geofence_radius_meters', sa.SmallInteger(), server_default=sa.text('30'), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_settings'))
    )
    op.create_table('system_alerts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('type', postgresql.ENUM('proxy_flagged', 'verification_failure_spike', 'system', 'other', name='alert_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_alerts'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('student', 'lecturer', 'admin', name='user_role'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending_approval', 'active', 'suspended', 'inactive', name='user_status'), server_default='pending_approval', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('venues',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('shape_type', postgresql.ENUM('circle', 'polygon', name='geofence_shape'), server_default='circle', nullable=False),
    sa.Column('boundary_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wifi_ssid', sa.String(), nullable=True),
    sa.Column('wifi_bssid', sa.String(), nullable=True),
    sa.Column('default_verification_method', postgresql.ENUM('gps_geofence', 'wifi_ap', name='verification_method'), server_default='gps_geofence', nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('credits', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_courses_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('course_code', name=op.f('uq_courses_course_code'))
    )
    op.create_table('lecturers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecturer_code', sa.String(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_lecturers_department_id_departments')),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_lecturers_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecturers')),
    sa.UniqueConstraint('lecturer_code', name=op.f('uq_lecturers_lecturer_code'))
    )
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_index_no', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('name_with_initials', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender_type'), nullable=False),
    sa.Column('nic', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('registered_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_students_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_students_department_id_departments')),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_students_id_users')),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], name=op.f('fk_students_registered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('nic', name=op.f('uq_students_nic')),
    sa.UniqueConstraint('student_index_no', name=op.f('uq_students_student_index_no'))
    )
    op.create_table('course_offerings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('offering_code', sa.String(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('lecturer_id', sa.Uuid(), nullable=False),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('day', sa.String(), server_default='Monday', nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('venue_id', sa.Uuid(), nullable=True),
    sa.Column('max_students', sa.SmallInteger(), nullable=True),
    sa.Column('late_threshold_minutes', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('random_check_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('random_check_window_minutes', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_course_offerings_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_offerings_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_course_offerings_created_by_users')),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], name=op.f('fk_course_offerings_lecturer_id_lecturers')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_course_offerings_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offerings'))
    )
    op.create_table('face_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('reference_photo_url', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_face_profiles_created_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_face_profiles_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_profiles'))
    )
    op.create_index('face_profiles_active_unique', 'face_profiles', ['student_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('chapters',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_chapters_course_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_chapters_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enrolled_by', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('unenrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_enrollments_course_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], name=op.f('fk_enrollments_enrolled_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_enrollments_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments'))
    )
    op.create_index('enrollments_active_unique', 'enrollments', ['student_id', 'course_offering_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('lecture_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=True),
    sa.Column('verification_method_override', postgresql.ENUM('gps_geofence', 'wifi_ap', name='verification_method'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_mins', sa.SmallInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'ongoing', 'completed', 'cancelled', name='session_status'), server_default='scheduled', nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_lecture_sessions_course_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_lecture_sessions_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_sessions'))
    )
    op.create_table('notices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('urgency', postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notice_urgency'), server_default='normal', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_roles', postgresql.ARRAY(postgresql.ENUM('student', 'lecturer', 'admin', name='user_role')), nullable=True),
    sa.Column('target_user_ids', postgresql.ARRAY(sa.Uuid()), nullable=True),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_notices_course_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_notices_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notices'))
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecture_session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('present', 'late', 'absent', 'flagged_proxy', name='attendance_status'), server_default='absent', nullable=False),
    sa.Column('first_check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('random_check_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('is_manually_overridden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('override_by', sa.Uuid(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_session_id'], ['lecture_sessions.id'], name=op.f('fk_attendance_records_lecture_session_id_lecture_sessions')),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], name=op.f('fk_attendance_records_override_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_records_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('lecture_session_id', 'student_id', name='attendance_records_unique')
    )
    op.create_table('course_materials',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_course_materials_chapter_id_chapters')),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_course_materials_course_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_course_materials_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_materials'))
    )
    op.create_table('notice_read_status',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('fk_notice_read_status_notice_id_notices')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notice_read_status_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice_read_status'))
    )
    op.create_table('recording_links',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecture_session_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', postgresql.ENUM('youtube', 'zoom', 'google_drive', 'onedrive', 'other', name='recording_platform'), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('upload_time', sa.Time(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_recording_links_added_by_users')),
    sa.ForeignKeyConstraint(['lecture_session_id'], ['lecture_sessions.id'], name=op.f('fk_recording_links_lecture_session_id_lecture_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recording_links'))
    )
    op.create_table('verification_windows',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecture_session_id', sa.Uuid(), nullable=False),
    sa.Column('window_type', postgresql.ENUM('check_in', 'random_check', name='window_type'), nullable=False),
    sa.Column('scheduled_open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_session_id'], ['lecture_sessions.id'], name=op.f('fk_verification_windows_lecture_session_id_lecture_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_windows'))
    )
    op.create_index('verification_windows_session_idx', 'verification_windows', ['lecture_session_id'], unique=False)
    op.create_table('attendance_verification_attempts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('verification_window_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('used_face_verification', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('used_location_check', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('location_method', postgresql.ENUM('gps_geofence', 'wifi_ap', name='verification_method'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('distance_from_venue_meters', sa.Numeric(), nullable=True),
    sa.Column('wifi_ssid_detected', sa.String(), nullable=True),
    sa.Column('face_match_confidence', sa.Numeric(), nullable=True),
    sa.Column('status', postgresql.ENUM('success', 'failed', name='attempt_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_verification_attempts_student_id_students')),
    sa.ForeignKeyConstraint(['verification_window_id'], ['verification_windows.id'], name=op.f('fk_attendance_verification_attempts_verification_window_id_verification_windows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_verification_attempts'))
    )
    op.create_index('attendance_verification_attempts_student_time_idx', 'attendance_verification_attempts', ['student_id', 'attempted_at'], unique=False)
    op.create_index('attendance_verification_attempts_window_student_idx', 'attendance_verification_attempts', ['verification_window_id', 'student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('attendance_verification_attempts_window_student_idx', table_name='attendance_verification_attempts')
    op.drop_index('attendance_verification_attempts_student_time_idx', table_name='attendance_verification_attempts')
    op.drop_table('attendance_verification_attempts')
    op.drop_index('verification_windows_session_idx', table_name='verification_windows')
    op.drop_table('verification_windows')
    op.drop_table('recording_links')
    op.drop_table('notice_read_status')
    op.drop_table('course_materials')
    op.drop_table('attendance_records')
    op.drop_table('notices')
    op.drop_table('lecture_sessions')
    op.drop_index('enrollments_active_unique', table_name='enrollments', postgresql_where=sa.text('is_active = true'))
    op.drop_table('enrollments')
    op.drop_table('chapters')
    op.drop_index('face_profiles_active_unique', table_name='face_profiles', postgresql_where=sa.text('is_active = true'))
    op.drop_table('face_profiles')
    op.drop_table('course_offerings')
    op.drop_table('students')
    op.drop_table('lecturers')
    op.drop_table('courses')
    op.drop_table('audit_logs')
    op.drop_table('venues')
    op.drop_table('users')
    op.drop_table('system_alerts')
    op.drop_table('platform_settings')
    op.drop_table('departments')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
